import Head from 'next/head';
import { Grid, GridItem, Show } from '@chakra-ui/react';

import GameListing from '@/features/games/GameListing';
import GenreSelector from '@/features/games/GenreSelector';
import useGameQuery from '@/features/games/useGameQuery';

export default function Home() {
	const { gameQuery, updateGameQuery } = useGameQuery();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Grid p={5} gap={10} templateColumns={{ base: '1fr', lg: '300px 1fr' }}>
				<GridItem>
					<Show above='lg'>
						<GenreSelector
							selectedGenre={gameQuery?.genres}
							onSelectGenre={(genres) => updateGameQuery({ genres })}
						/>
					</Show>
				</GridItem>
				<GridItem>
					<GameListing />
				</GridItem>
			</Grid>
		</>
	);
}
