import Head from 'next/head';
import { Grid, GridItem, Show } from '@chakra-ui/react';

import AppLayout from '@/layouts/AppLayout';
import GameListing from '@/feature/games/GameListing';
import GenreSelector from '@/feature/games/GenreSelector';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<AppLayout>
				<Grid p={5} gap={5} templateColumns={{ base: '1fr', lg: '300px 1fr' }}>
					<Show above='lg'>
						<GridItem>
							<GenreSelector />
						</GridItem>
					</Show>
					<GridItem>
						<GameListing />
					</GridItem>
				</Grid>
			</AppLayout>
		</>
	);
}
