import Head from 'next/head';
import { Grid, GridItem, Heading, Show } from '@chakra-ui/react';

import AppLayout from '@/layouts/AppLayout';
import GameListing from '@/features/games/GameListing';
import GenreSelector from '@/features/games/GenreSelector';
import useGameQuery from '@/features/games/useGameQuery';

export default function Home() {
	const { gameQuery, updateGameQuery } = useGameQuery();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<AppLayout>
				<Grid p={5} gap={5} templateColumns={{ base: '1fr', lg: '300px 1fr' }}>
					<Show above='lg'>
						<GridItem>
							<Heading size='md' mb={5}>
								Genres
							</Heading>
							<GenreSelector
								selectedGenre={gameQuery?.genres}
								onSelectGenre={(genres) => updateGameQuery({ genres })}
							/>
						</GridItem>
					</Show>
					<GridItem>
						<GameListing />
					</GridItem>
				</Grid>
			</AppLayout>
		</>
	);
}
